# Generated by Django 5.2.1 on 2025-05-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Наименование партнера')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('source', models.CharField(choices=[('vendor', 'Вендор'), ('search', 'Поисковая система'), ('social', 'Социальные сети'), ('other', 'Другое')], max_length=50, verbose_name='Как вы нас нашли?')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('subscribe_newsletter', models.BooleanField(default=False, verbose_name='Получать рассылку')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Согласие с условиями')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на партнерство',
                'verbose_name_plural': 'Заявки на партнерство',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='PartnerRequest',
        ),
    ]
