# Generated by Django 5.2.1 on 2025-06-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_partnershiprequest_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Как вы нас нашли?'),
        ),
    ]
