# Generated by Django 5.2.1 on 2025-06-30 23:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_partnershiprequest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='address',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='comments',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='partner_name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Наименование партнера'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='source',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Как вы нас нашли?'),
        ),
    ]
