# Generated by Django 5.2.1 on 2025-05-22 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Наименование партнера')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Наименование заказчика')),
                ('vendor', models.CharField(choices=[('vendor1', 'Вендор 1'), ('vendor2', 'Вендор 2'), ('other', 'Другой')], max_length=100, verbose_name='Вендор')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='projects/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Прикрепленный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект для реализации',
                'verbose_name_plural': 'Проекты для реализации',
                'ordering': ['-created_at'],
            },
        ),
    ]
