# Generated by Django 5.2.1 on 2025-06-15 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_news_is_registration_available'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.vendor', verbose_name='Вендор'),
        ),
    ]
