# Generated by Django 5.2.1 on 2025-06-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_news_is_registration_available'),
        ('core', '0002_alter_projectproposal_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/attachments/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.vendor', verbose_name='Вендор'),
            preserve_default=False,
        ),
    ]
