# Generated by Django 5.2.1 on 2025-06-30 23:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projectproposal_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='comments',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='customer_name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Наименование заказчика'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='partner_name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Наименование партнера'),
        ),
    ]
