# Generated by Django 5.2.1 on 2025-05-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория вендора',
                'verbose_name_plural': 'Категории вендоров',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Вендор', 'verbose_name_plural': 'Вендоры'},
        ),
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, to='content.vendorcategory', verbose_name='Категории для сортировки'),
        ),
    ]
