# Generated by Django 5.2.1 on 2025-06-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_vendorcategory_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='speakers',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
