# Generated by Django 5.2.1 on 2025-06-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_news_speakers_delete_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_registration_available',
            field=models.BooleanField(default=False, verbose_name='Доступна регистрация'),
        ),
        migrations.CreateModel(
            name='NewsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='content.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Регистрация на новость',
                'verbose_name_plural': 'Регистрации на новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
