# Generated by Django 5.2.1 on 2025-06-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_news_is_registration_available_newsregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_registration_available',
        ),
    ]
